#!/usr/bin/env bash
# lib/project/workspace.sh -- Multi-service workspace support.
# Requires: common.sh sourced

[[ -n "${_WORKSPACE_SH_LOADED:-}" ]] && return 0
_WORKSPACE_SH_LOADED=1

# Creates the workspace skeleton (idempotent).
# Called only once -- when creating the first service.
workspace_init() {
  local workspace_path="$1"
  local name="$2"

  if [[ -d "${workspace_path}/services" ]]; then
    log "Workspace already exists: ${workspace_path}"
    return 0
  fi

  log "Creating workspace '${name}'"

  mkdir -p "${workspace_path}/services"
  mkdir -p "${workspace_path}/.devcontainer"

  local net_name="${name}-net"

  # ---- compose.yaml ----
  local compose_file="${workspace_path}/compose.yaml"
  if [[ ! -f "$compose_file" ]]; then
    cat > "$compose_file" <<COMPOSEYAML
services: {}

networks:
  default:
    name: ${net_name}
COMPOSEYAML
  fi

  # ---- .env.example ----
  local env_example="${workspace_path}/.env.example"
  if [[ ! -f "$env_example" ]]; then
    cat > "$env_example" <<'ENVEOF'
# Environment variables -- copy to .env and adjust values.
# .env is NOT versioned (.gitignore). .env.example is reference.
ENVEOF
  fi

  # Ensure .env exists (may be empty) so compose env_file: .env works.
  [[ -f "${workspace_path}/.env" ]] || touch "${workspace_path}/.env"

  # ---- .gitignore ----
  if [[ ! -f "${workspace_path}/.gitignore" ]]; then
    cat > "${workspace_path}/.gitignore" <<'GITIGNORE'
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.eggs/

# Virtual envs
.venv/
venv/

# IDE
.idea/
*.swp
*.swo

# Environment
.env

# Pytest / Coverage
.pytest_cache/
.ruff_cache/
htmlcov/
.coverage
GITIGNORE
  fi

  # ---- README.md ----
  if [[ ! -f "${workspace_path}/README.md" ]]; then
    cat > "${workspace_path}/README.md" <<READMEEOF
# ${name}

Multi-service workspace generated by [dropwsl](https://github.com/yurifranconeri/dropwsl).

## Services

Each service lives in \`services/<name>/\` with its own Dockerfile and tests.

## Development

\`\`\`bash
# Start infrastructure (postgres, redis, etc.)
docker compose up -d

# Open a service in VS Code:
# Ctrl+Shift+P > Dev Containers: Reopen in Container > choose the service
\`\`\`

## Infrastructure

Infrastructure services defined in \`compose.yaml\`.
Environment variables in \`.env\` (copy from \`.env.example\`).
READMEEOF
  fi

  # ---- git init ----
  if [[ ! -d "${workspace_path}/.git" ]]; then
    run_quiet git -C "$workspace_path" init
  fi
}

# Gera .devcontainer/<service>/ com devcontainer.json compose-based.
workspace_devcontainer() {
  local workspace_path="$1"
  local service="$2"
  local name="$3"
  local lang="${4:-python}"

  local devcontainer_dir="${workspace_path}/.devcontainer/${service}"
  mkdir -p "$devcontainer_dir"

  # ---- devcontainer.json (compose-based) ----
  if [[ ! -f "${devcontainer_dir}/devcontainer.json" ]]; then
    cat > "${devcontainer_dir}/devcontainer.json" <<DCJSON
{
  "name": "${service} (${name})",
  "dockerComposeFile": "../../compose.yaml",
  "service": "${service}",
  "workspaceFolder": "/workspaces/${name}/services/${service}",
  "shutdownAction": "none",
  "overrideCommand": true,

  "remoteUser": "vscode",
  "updateRemoteUserUID": true,

  "containerEnv": {
    "PYTHONDONTWRITEBYTECODE": "1",
    "PYTHONUNBUFFERED": "1"
  },

  "customizations": {
    "vscode": {
      "extensions": [
        "ms-python.python",
        "ms-python.vscode-pylance",
        "charliermarsh.ruff",
        "GitHub.copilot-chat",
        "EditorConfig.EditorConfig",
        "eamodio.gitlens",
        "ms-azuretools.vscode-docker"
      ],
      "settings": {
        "[python]": {
          "editor.defaultFormatter": "charliermarsh.ruff",
          "editor.formatOnSave": true
        },
        "python.defaultInterpreterPath": "/opt/venv/bin/python",
        "python.testing.pytestEnabled": true,
        "python.testing.pytestArgs": ["tests"],
        "terminal.integrated.defaultProfile.linux": "bash",
        "terminal.integrated.profiles.linux": {
          "bash": { "path": "/bin/bash" }
        }
      }
    }
  },

  "postCreateCommand": "bash /workspaces/${name}/.devcontainer/${service}/post-create.sh",
  "postStartCommand": "sudo chmod 666 /var/run/docker.sock 2>/dev/null || true"
}
DCJSON
  fi

  # ---- Dockerfile (dev container) ----
  # Copy from template if available, otherwise create minimal
  local templates_dir
  templates_dir="$(find_templates_dir)"
  local template_dockerfile="${templates_dir}/${lang}/.devcontainer/Dockerfile"
  if [[ -f "$template_dockerfile" ]] && [[ ! -f "${devcontainer_dir}/Dockerfile" ]]; then
    cp "$template_dockerfile" "${devcontainer_dir}/Dockerfile"
  fi

  # ---- post-create.sh ----
  local template_postcreate="${templates_dir}/${lang}/.devcontainer/post-create.sh"
  if [[ -f "$template_postcreate" ]] && [[ ! -f "${devcontainer_dir}/post-create.sh" ]]; then
    cp "$template_postcreate" "${devcontainer_dir}/post-create.sh"
  fi
}

# Injects the application service into the workspace compose.yaml.
workspace_compose_service() {
  local workspace_path="$1"
  local service="$2"
  local name="$3"
  local host_port="$4"

  local compose_file="${workspace_path}/compose.yaml"
  [[ -f "$compose_file" ]] || return 0

  # Idempotency
  if grep -Fq "  ${service}:" "$compose_file"; then
    log "Service '${service}' already exists in compose.yaml"
    return 0
  fi

  local service_block="    build:
      context: services/${service}
      dockerfile: ../../.devcontainer/${service}/Dockerfile
    env_file: .env
    volumes:
      - .:/workspaces/${name}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspaces/${name}/services/${service}
    command: sleep infinity
    ports:
      - \"${host_port}:8000\""

  inject_compose_service "$workspace_path" "$service" "$service_block" ""
}

# Calculates the next available port for a service.
_workspace_next_port() {
  local workspace_path="$1"
  local count=0
  if [[ -d "${workspace_path}/services" ]]; then
    count=$(find "${workspace_path}/services" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
  fi
  echo $((8000 + count + 1))
}

