"""Streamlit Showcase -- demonstration of all available components."""

from datetime import date, datetime, time

import numpy as np
import pandas as pd
import streamlit as st

st.set_page_config(page_title="{{PROJECT_NAME}}", page_icon="🚀", layout="wide")

# ---- Sidebar (global settings + input widgets) ----
st.sidebar.header("⚙️ Settings")
user_name = st.sidebar.text_input("Your name", value="World")
palette = st.sidebar.radio("Color palette", ["Default", "Ocean", "Neon"])
CHART_COLORS: dict[str, list[str] | None] = {
    "Default": None,
    "Ocean": ["#264653", "#2a9d8f", "#e76f51"],
    "Neon": ["#ff006e", "#8338ec", "#3a86ff"],
}
chart_colors: list[str] | None = CHART_COLORS[palette]
show_code = st.sidebar.toggle("Show code examples", value=False)
st.sidebar.divider()
st.sidebar.caption("Showcase generated by dropwsl")

# ---- Header ----
st.title("{{PROJECT_NAME}} 🚀")
st.markdown(
    "**Complete showcase** of Streamlit components. "
    "Explore each tab to see working examples of all widgets, "
    "charts, layouts and available elements."
)

# ---- Main tabs ----
tab_widgets, tab_data, tab_charts, tab_layout, tab_chat, tab_status, tab_forms = st.tabs(
    ["🎛️ Widgets", "📊 Data", "📈 Charts", "📐 Layout", "💬 Chat", "📢 Status", "📝 Forms"]
)

# ================================================================
# TAB 1: WIDGETS -- all native input widgets
# ================================================================
with tab_widgets:
    st.header("Input Widgets")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.subheader("Text")
        text_val = st.text_input("Text input", placeholder="Type something...")
        area_val = st.text_area("Text area", placeholder="Long text here...")
        if text_val:
            st.write(f"You typed: {text_val}")

    with col2:
        st.subheader("Numbers and Dates")
        num = st.number_input("Number", min_value=0, max_value=100, value=42)
        slider_val = st.slider("Slider", 0, 100, 50)
        range_val = st.slider("Range slider", 0.0, 100.0, (25.0, 75.0))
        date_val = st.date_input("Date", value=date.today())
        time_val = st.time_input("Time", value=time(9, 0))

    with col3:
        st.subheader("Selection")
        select = st.selectbox("Selectbox", ["Python", "JavaScript", "Go", "Rust"])
        multi = st.multiselect(
            "Multiselect", ["FastAPI", "Django", "Flask", "Streamlit"], default=["FastAPI"]
        )
        radio_val = st.radio("Radio", ["Option A", "Option B", "Option C"], horizontal=True)

    st.divider()

    col4, col5, col6 = st.columns(3)

    with col4:
        st.subheader("Toggles and Checks")
        check = st.checkbox("Checkbox", value=True)
        toggle_val = st.toggle("Toggle", value=False)
        color = st.color_picker("Color", value="#FF4B4B")
        st.write(f"Selected color: {color}")

    with col5:
        st.subheader("Select Slider")
        size = st.select_slider("Size", options=["XS", "S", "M", "L", "XL"], value="M")
        st.write(f"Selected: {size}")

    with col6:
        st.subheader("Upload and Feedback")
        uploaded = st.file_uploader("File upload", type=["csv", "txt", "json"])
        if uploaded:
            st.success(f"File received: {uploaded.name} ({uploaded.size} bytes)")
        feedback_val = st.feedback("stars")
        if feedback_val is not None:
            st.write(f"Feedback: {'⭐' * (feedback_val + 1)}")

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'text_val = st.text_input("Text input", placeholder="...")\n'
                'slider_val = st.slider("Slider", 0, 100, 50)\n'
                'select = st.selectbox("Selectbox", ["Python", "JavaScript"])\n'
                'uploaded = st.file_uploader("Upload", type=["csv"])',
                language="python",
            )

# ================================================================
# TAB 2: DATA -- dataframe, data_editor, metric, json, table
# ================================================================
with tab_data:
    st.header("Data Elements")

    # Metrics
    st.subheader("Metrics")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Revenue", "$12.4k", "+8.2%")
    m2.metric("Users", "1,234", "+12%")
    m3.metric("Latency", "42ms", "-5ms")
    m4.metric("Uptime", "99.9%", "+0.1%")

    st.divider()

    # Interactive DataFrame vs static table
    df = pd.DataFrame(
        {
            "Name": ["Alice", "Bob", "Carol", "David", "Eva"],
            "Age": [30, 25, 35, 28, 32],
            "Salary": [8500, 6200, 9800, 7100, 8900],
            "Active": [True, False, True, True, False],
            "Start Date": [
                date(2020, 1, 15),
                date(2021, 3, 22),
                date(2019, 7, 10),
                date(2022, 11, 5),
                date(2023, 2, 28),
            ],
        }
    )

    col_df, col_table = st.columns(2)

    with col_df:
        st.subheader("Interactive DataFrame")
        st.dataframe(df, width="stretch", hide_index=True)

    with col_table:
        st.subheader("Static table")
        st.table(df.head(3))

    st.divider()

    # Data editor
    st.subheader("Data Editor (editable)")
    edited_df = st.data_editor(
        df,
        num_rows="dynamic",
        width="stretch",
        column_config={
            "Salary": st.column_config.NumberColumn("Salary ($)", format="$ %d"),
            "Active": st.column_config.CheckboxColumn("Active?"),
            "Start Date": st.column_config.DateColumn("Start Date", format="YYYY-MM-DD"),
        },
    )

    st.divider()

    # JSON
    st.subheader("JSON viewer")
    st.json(
        {
            "project": "{{PROJECT_NAME}}",
            "version": "0.1.0",
            "config": {"debug": True, "workers": 4, "tags": ["demo", "showcase"]},
        }
    )

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'st.metric("Revenue", "$12.4k", "+8.2%")\n'
                'st.dataframe(df, use_container_width=True)\n'
                "edited_df = st.data_editor(df, num_rows=\"dynamic\")\n"
                'st.json({"key": "value"})',
                language="python",
            )

# ================================================================
# TAB 3: CHARTS -- line, bar, area, scatter, map
# ================================================================
with tab_charts:
    st.header("Native Charts")

    chart_data = pd.DataFrame(
        np.random.randn(30, 3), columns=["Sales", "Costs", "Profit"]
    )

    col_c1, col_c2 = st.columns(2)

    with col_c1:
        st.subheader("Line Chart")
        st.line_chart(chart_data, color=chart_colors)  # type: ignore[arg-type]

        st.subheader("Area Chart")
        st.area_chart(chart_data, color=chart_colors)  # type: ignore[arg-type]

    with col_c2:
        st.subheader("Bar Chart")
        st.bar_chart(chart_data, color=chart_colors)  # type: ignore[arg-type]

        st.subheader("Scatter Chart")
        scatter_data = pd.DataFrame(
            {
                "x": np.random.randn(100),
                "y": np.random.randn(100),
                "size": np.random.rand(100) * 50,
            }
        )
        st.scatter_chart(scatter_data, x="x", y="y", size="size")

    st.divider()

    # Map
    st.subheader("Map")
    map_data = pd.DataFrame(
        np.random.randn(50, 2) / [50, 50] + [-23.55, -46.63],
        columns=["lat", "lon"],
    )
    st.map(map_data)

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                "chart_data = pd.DataFrame(np.random.randn(30, 3), columns=[...])\n"
                "st.line_chart(chart_data)\n"
                "st.bar_chart(chart_data)\n"
                'st.scatter_chart(scatter_data, x="x", y="y", size="size")\n'
                "st.map(map_data)",
                language="python",
            )

# ================================================================
# TAB 4: LAYOUT -- columns, expander, popover, container, tabs
# ================================================================
with tab_layout:
    st.header("Layout and Containers")

    # Columns with different proportions
    st.subheader("Columns (proportions 2:1:1)")
    c1, c2, c3 = st.columns([2, 1, 1])
    c1.info("Wide column (2x)")
    c2.warning("Medium column")
    c3.error("Narrow column")

    st.divider()

    # Expander
    st.subheader("Expander")
    with st.expander("Click to expand", expanded=False):
        st.write("Hidden content that appears when expanded.")
        st.code(
            'with st.expander("Title"):\n    st.write("Hidden content")',
            language="python",
        )

    # Popover
    st.subheader("Popover")
    with st.popover("⚙️ Open settings"):
        st.write("Popover content:")
        config_opt = st.checkbox("Enable feature X", key="popover_check")
        st.write(f"Feature X: {'ON' if config_opt else 'OFF'}")

    st.divider()

    # Nested tabs
    st.subheader("Nested tabs")
    inner1, inner2 = st.tabs(["Sub-tab A", "Sub-tab B"])
    with inner1:
        st.write("Sub-tab A content")
        st.image("https://placehold.co/400x100/EEE/31343C?text=Placeholder+A", width=400)
    with inner2:
        st.write("Sub-tab B content")
        st.image("https://placehold.co/400x100/EEE/31343C?text=Placeholder+B", width=400)

    # Fixed-height container
    st.subheader("Scrollable container")
    with st.container(height=150):
        for i in range(20):
            st.text(f"Line {i + 1} -- content in a vertically scrollable container")

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'c1, c2, c3 = st.columns([2, 1, 1])\n'
                'with st.expander("Title"):\n    st.write("...")\n'
                'with st.popover("Config"):\n    st.checkbox("Feature X")\n'
                "with st.container(height=150):\n    st.text(...)",
                language="python",
            )

# ================================================================
# TAB 5: CHAT -- chat_message + chat_input + session_state
# ================================================================
with tab_chat:
    st.header("Chat Elements")
    st.caption(
        "Demonstration of Streamlit chat elements. "
        "This is an echo bot -- replace with your LLM call."
    )

    if "messages" not in st.session_state:
        st.session_state.messages = [
            {"role": "assistant", "content": "Hello! How can I help? 👋"}
        ]

    chat_container = st.container(height=400)
    with chat_container:
        for msg in st.session_state.messages:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])

    if prompt := st.chat_input("Type a message...", key="showcase_chat"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        # TODO: replace with your LLM client (e.g., Azure OpenAI, OpenAI, etc.)
        response = f"Echo: {prompt}"
        st.session_state.messages.append({"role": "assistant", "content": response})
        st.rerun()

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'if "messages" not in st.session_state:\n'
                "    st.session_state.messages = []\n\n"
                "for msg in st.session_state.messages:\n"
                '    with st.chat_message(msg["role"]):\n'
                '        st.markdown(msg["content"])\n\n'
                'if prompt := st.chat_input("Message..."):\n'
                '    st.session_state.messages.append({"role": "user", "content": prompt})\n'
                "    # Call your LLM here\n"
                "    st.rerun()",
                language="python",
            )

# ================================================================
# TAB 6: STATUS -- alerts, progress, toast, balloons, spinner
# ================================================================
with tab_status:
    st.header("Status and Alerts")

    col_s1, col_s2 = st.columns(2)

    with col_s1:
        st.subheader("Alerts")
        st.success("Operation completed successfully!")
        st.info("Info: dataset is updated daily.")
        st.warning("Warning: required field is empty.")
        st.error("Error: database connection failed.")

        with st.expander("Exception (example)"):
            st.code(
                'try:\n'
                '    result = 1 / 0\n'
                'except ZeroDivisionError as e:\n'
                '    st.exception(e)  # displays formatted traceback',
                language="python",
            )

    with col_s2:
        st.subheader("Progress and Animations")
        st.progress(75, text="Processing... 75%")

        if st.button("🎈 Balloons!", key="btn_balloons"):
            st.balloons()
        if st.button("❄️ Snow!", key="btn_snow"):
            st.snow()
        if st.button("🍞 Toast!", key="btn_toast"):
            st.toast("Toast notification!", icon="✅")

    st.divider()

    # Status container (simulates long-running)
    st.subheader("Status Container")
    if st.button("▶️ Run simulated task", key="btn_status"):
        with st.status("Processing...", expanded=True) as status:
            st.write("Step 1: Loading data...")
            st.write("Step 2: Processing...")
            st.write("Step 3: Finishing...")
            status.update(label="Done!", state="complete", expanded=False)

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'st.success("Success message")\n'
                'st.info("Informational message")\n'
                'st.warning("Warning message")\n'
                'st.error("Error message")\n'
                "st.progress(75)\n"
                "st.balloons()\n"
                'st.toast("Notification!", icon="✅")\n'
                'with st.status("Processing..."):\n    st.write("Step 1...")',
                language="python",
            )

# ================================================================
# TAB 7: FORMS -- st.form + download_button + link_button
# ================================================================
with tab_forms:
    st.header("Forms and Downloads")

    # Form
    st.subheader("Form (batch submit)")
    with st.form("registration_form"):
        f_name = st.text_input("Full name")
        f_email = st.text_input("Email")
        f_role = st.selectbox("Role", ["Developer", "Designer", "PM", "QA"])
        f_agree = st.checkbox("I accept the terms")
        submitted = st.form_submit_button("Submit")
        if submitted:
            if f_name and f_email and f_agree:
                st.success(f"Registration received: {f_name} ({f_email}) -- {f_role}")
            else:
                st.error("Fill in all fields and accept the terms.")

    st.divider()

    # Download button
    st.subheader("Download")
    sample_csv = df.to_csv(index=False)
    st.download_button(
        "📥 Download sample CSV",
        data=sample_csv,
        file_name="data.csv",
        mime="text/csv",
    )

    # Link button
    st.link_button("📖 Streamlit Documentation", "https://docs.streamlit.io")

    if show_code:
        with st.expander("📝 Source code for this section"):
            st.code(
                'with st.form("my_form"):\n'
                '    name = st.text_input("Name")\n'
                '    submitted = st.form_submit_button("Submit")\n'
                "    if submitted:\n"
                '        st.success(f"Received: {name}")\n\n'
                'st.download_button("Download", data=csv, file_name="data.csv")\n'
                'st.link_button("Docs", "https://docs.streamlit.io")',
                language="python",
            )

# ---- Footer ----
st.divider()
st.caption(
    f"Hello, {user_name}! • Palette: {palette} • "
    f"Generated at {datetime.now():%Y-%m-%d %H:%M}"
)
